[package]
name = "game-collection-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "^4", default-features = false, features = [ "rustls" ] }
sqlx = { version = "^0", default-features = false, features = [ "macros", "runtime-actix-rustls", "postgres", "chrono" ] }
sea-query = { version = "^0", default-features = false, features = [ "derive", "backend-postgres", "with-chrono" ] }
chrono = { version = "^0", default-features = false, features = [ "serde" ] }
iso8601 = { version = "^0", default-features = false }

# Authentication
actix-web-httpauth = { version = "^0", default-features = false }
jsonwebtoken = { version = "^8", default-features = false }
base64 = { version = "^0.13", default-features = false }
uuid = { version = "^1", default-features = false, features = [ "v4" ] }
bcrypt = { version = "^0", default-features = false, features = [ "std" ] }

# TLS
rustls = { version = "^0", default-features = false }
rustls-pemfile = { version = "^1", default-features = false }

# Serialisation/Deserialisation
serde = { version = "^1", default-features = false }
serde_json = { version = "^1", default-features = false }

# Image
actix-multipart = { version = "^0", default-features = false }
futures = { version = "^0", default-features = false }
hyper = { version= "^0", default-features = false }
url = { version = "^2", default-features = false }

# Environment variables
dotenvy = { version = "^0", default-features = false }

# Logging
log = { version = "^0", default-features = false }
env_logger = { version = "^0", default-features = false }

# OpenAPI
utoipa = { version = "^2", default-features = false, features = [ "actix_extras", "chrono" ] }
utoipa-swagger-ui = { version = "^2", default-features = false, features = [ "actix-web" ] }