version: '3.8'

services:
  app:
    image: n2tmad/game-col:0.1.0
    container_name: game-col-server_app
    hostname: game-col-server
    restart: always
    environment:
      #- APP_KEY=9jo1258AFGRgISUdT4LvBlhiZoN2C1Ck
      #- DB_CONNECTION=mysql
      - SECRET_KEY=CRtFiv7L2jxqtYW6EQiDyEj4e8E0pkZibKfuACxwSRFfGyhNZc
      - DB_USER=game-col
      - DB_PASSWORD=63F1oz7zw8Dcxcgb4gxbHzeN3cuHQl
      - DB_HOST=192.168.10.147
      - DB_PORT=5432
      - DB_DATABASE=game-col_new
    ports:
      - 8080:80
    networks:
      - net

networks:
  net:
    name: game-col-server_net