pub mod auth_service;
mod base;
pub mod dlc_available_service;
pub mod dlc_finishes_service;
pub mod dlcs_service;
pub mod game_available_service;
pub mod game_finishes_service;
pub mod game_logs_service;
pub mod game_tags_service;
pub mod games_service;
pub mod platforms_service;
pub mod tags_service;
pub mod users_service;
