name: Build CI

on:
  # Triggers the workflow on push or pull request events but only for the default branch
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  analysis:
    name: Analysis
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Setup rust environment
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: nightly-2024-02-04
          components: rustfmt, clippy

      - name: Get dependencies
        run: cargo install cargo-audit cargo-outdated
      # cargo-deny cargo-udeps

      - name: Analyse with clippy
        run: cargo clippy --message-format json > clippy-report.json
      - name: Analyse with audit
        run: cargo audit --json > audit-report.json
        continue-on-error: true
      - name: Analyse with outdated
        run: cargo outdated --workspace --depth 1 --format json > outdated-report.json
      # - run: cargo deny init && cargo deny --format json check 2> deny-report.json
      #   continue-on-error: true
      # - run: cargo udeps --quiet --workspace --all-features --all-targets --output json > udeps-report.json

      - name: Create reports artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: reports
          path: |
            clippy-report.json
            audit-report.json
            outdated-report.json
          # deny-report.json
          # udeps-report.json

  sonar:
    name: Sonar
    needs: analysis
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Download reports artifact
        uses: actions/download-artifact@v4.1.4
        with:
          name: reports

      - name: Setup rust environment
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: nightly-2024-02-04
          components: rustfmt, clippy

      - name: Get dependencies
        run: cargo install cargo-sonar

      - name: Transform reports
        run: |
          cargo sonar --clippy --clippy-path clippy-report.json --sonar-path sonar-clippy-report.json
          cargo sonar --audit --audit-path audit-report.json --sonar-path sonar-audit-report.json
          cargo sonar --outdated --outdated-path outdated-report.json --sonar-path sonar-outdated-report.json
      #    cargo sonar --deny --deny-path deny-report.json --sonar-path sonar-deny-report.json
      #    cargo sonar --udeps --udeps-path udeps-report.json --sonar-path sonar-udeps-report.json

      - name: Fix audit report
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: '"filePath":"[\w\/\-\.]*"'
          replace: '"filePath":"Cargo.lock"'
          include: '**sonar-audit-report.json'
          regex: true
      - name: Fix outdated report
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: '"filePath":"[\w\/\-\.]*"'
          replace: '"filePath":"Cargo.lock"'
          include: '**sonar-outdated-report.json'
          regex: true

      - name: Upload reports to sonar
        uses: SonarSource/sonarcloud-github-action@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.externalIssuesReportPaths=sonar-clippy-report.json,sonar-audit-report.json,sonar-outdated-report.json
          # ,sonar-deny-report.json,sonar-udeps-report.json

      - name: Create sonar reports artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: sonar-reports
          path: |
            sonar-clippy-report.json
            sonar-audit-report.json
            sonar-outdated-report.json
          # sonar-deny-report.json
          # sonar-udeps-report.json

  build:
    name: Build
    needs: analysis
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup rust environment
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: nightly-2024-02-04
          components: rustfmt, clippy

      - name: Build executable
        run: cargo build --release
